sudo: false

language: ruby

env:
  - secure: "HswxrOJpdVA+i26zbpi47w9GsS25ix8w8gu+9GSi7tJ5AuWrBvVWV2PQ9CN1kVILzQFou1c/PeCyijvN5xudnRC7bRQETYazVfAUO5Fpu6UhYO1YQL69oo+vVzgLwVRicn5Pj3/sCR6McHekFe4Tt08tYM3oj3apA37qxeWx0Dw="
script:
  - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  - ./deploy.sh
